import React from "react";
import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  ArrowRight,
  Atom,
  Beaker,
  Binary,
  BookOpen,
  Box,
  Braces,
  BrainCircuit,
  Bug,
  Cable,
  Calculator,
  ChartLine,
  CircuitBoard,
  Clock,
  Cloud,
  Code,
  Cog,
  Compass,
  Cpu,
  Database,
  Disc,
  Dna,
  FileText,
  Filter,
  FlaskConical,
  Folder,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  HardDrive,
  Hash,
  Infinity as InfinityIcon,
  Key,
  Layers,
  Lightbulb,
  Lock,
  Magnet,
  MemoryStick,
  Microscope,
  Monitor,
  MousePointer,
  Network,
  Orbit,
  Package,
  Pi,
  Radio,
  RefreshCw,
  Repeat,
  Rocket,
  Ruler,
  Scale,
  Search,
  Server,
  Settings,
  Shield,
  Shuffle,
  Sigma,
  Smartphone,
  Sparkles,
  SquareFunction,
  Table,
  Target,
  Telescope,
  Terminal,
  TestTube,
  Thermometer,
  Timer,
  TrendingUp,
  Triangle,
  Unlock,
  Usb,
  Variable,
  Waves,
  Wifi,
  Workflow,
  Wrench,
  X,
  Zap,
} from "lucide-react";
import { colors } from "../style/tokens";

/**
 * Allow-listed lucide icon, addressed by a stable kebab-case name so the
 * blueprint LLM can request icons by string without ever importing lucide
 * itself (Custom scenes import only the barrel). An unknown name renders
 * nothing — the pipeline validates against ICON_NAMES before it gets here.
 */
const ICONS: Record<string, React.ComponentType<{ size?: number | string; color?: string; strokeWidth?: number }>> = {
  activity: Activity,
  alert: AlertTriangle,
  "arrow-right": ArrowRight,
  atom: Atom,
  beaker: Beaker,
  binary: Binary,
  book: BookOpen,
  box: Box,
  braces: Braces,
  brain: BrainCircuit,
  bug: Bug,
  cable: Cable,
  calculator: Calculator,
  chart: ChartLine,
  circuit: CircuitBoard,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  cog: Cog,
  compass: Compass,
  cpu: Cpu,
  database: Database,
  disc: Disc,
  dna: Dna,
  exchange: ArrowLeftRight,
  file: FileText,
  filter: Filter,
  flask: FlaskConical,
  folder: Folder,
  function: SquareFunction,
  gauge: Gauge,
  git: GitBranch,
  globe: Globe,
  graduation: GraduationCap,
  hash: Hash,
  infinity: InfinityIcon,
  key: Key,
  layers: Layers,
  lightbulb: Lightbulb,
  lock: Lock,
  magnet: Magnet,
  memory: MemoryStick,
  microscope: Microscope,
  monitor: Monitor,
  network: Network,
  orbit: Orbit,
  package: Package,
  pi: Pi,
  pointer: MousePointer,
  radio: Radio,
  refresh: RefreshCw,
  repeat: Repeat,
  rocket: Rocket,
  ruler: Ruler,
  scale: Scale,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  shuffle: Shuffle,
  sigma: Sigma,
  smartphone: Smartphone,
  sparkles: Sparkles,
  storage: HardDrive,
  table: Table,
  target: Target,
  telescope: Telescope,
  terminal: Terminal,
  "test-tube": TestTube,
  thermometer: Thermometer,
  timer: Timer,
  trending: TrendingUp,
  triangle: Triangle,
  unlock: Unlock,
  usb: Usb,
  variable: Variable,
  waves: Waves,
  wifi: Wifi,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  zap: Zap,
};

export const ICON_NAMES = Object.keys(ICONS).sort();

export const Icon: React.FC<{
  name: string;
  size?: number;
  color?: string;
  opacity?: number;
  strokeWidth?: number;
}> = ({ name, size = 32, color = colors.text, opacity = 1, strokeWidth = 2 }) => {
  const Cmp = ICONS[name];
  if (!Cmp) {
    return null;
  }
  return (
    <span style={{ display: "inline-flex", opacity, lineHeight: 0 }}>
      <Cmp size={size} color={color} strokeWidth={strokeWidth} />
    </span>
  );
};
